# -*- coding: utf-8 -*-
"""Copia de Copia de Copia de Copia de Copia de limpiezaPolla.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/112jlpIBMvz0sw_A6pPTOjQ6woNpYcW09
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy                 as np
import pandas                as pd
import matplotlib.pyplot     as plt



data = pd.read_excel(r'C:\Users\Usuario\OneDrive - BAMBOO ANALYTICS SAS\Escritorio\datosPollaMundial\resultadosHastaAhora.xlsx')

#Configuración inicial
ind_Col=0
ind_Row=9

Pais1_Col=1
Pais1_Row=11

Pais2_Col=2
Pais2_Row=11

Marca1_Col=1
Marca1_Row=12

Marca2_Col=2
Marca2_Row=12

lista = []

for row in range(0,6):
  for group in range(0,8):
    ind_Col=0+group*3
    ind_Row=9+row*5

    Pais1_Col=1+group*3
    Pais1_Row=11+row*5

    Pais2_Col=2+group*3
    Pais2_Row=11+row*5

    Marca1_Col=1+group*3
    Marca1_Row=12+row*5

    Marca2_Col=2+group*3
    Marca2_Row=12+row*5
    
    lista.append([data.iat[ind_Row,ind_Col],
            data.iat[Pais1_Row,Pais1_Col],
            data.iat[Pais2_Row,Pais2_Col],
            data.iat[Marca1_Row,Marca1_Col],
            data.iat[Marca2_Row,Marca2_Col]])

df= pd.DataFrame(lista, columns = ['ID','Equipo 1','Equipo 2','Resultado 1','Resultado 2'])

df



file_name = 'resultadosDeVerdad.xlsx'
df.to_excel(file_name)